
#必需要加instance-id和hostname，不加instance-id注册后不显示ip，不加hostname，其它服务调用时，取不到真实IP
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册实例
    hostname: ${spring.cloud.client.ip-address}   #实际IP,通过请求调用时真实地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8071

spring:
  application:
    name: product-server

